### ISSUE TITLE
FAIL_NAME_ALREADY_ONLINE triggered if name partially matches an online player

### ISSUE THREAD

**Issue by sk8ingDuck** [iiAhmedYT/ModernDisguise#9]
Hi,
my ingame name is 'sk8ingDuck' and I'm trying to nick myself as 'sk8ing' 

I'm using this code:
```
Disguise.Builder builder = Disguise.builder();
builder.setName("sk8ing");
DisguiseManager.getProvider().disguise(Bukkit.getPlayer("sk8ingDuck"), builder.build());
```

But the DisguiseResponse is `FAIL_NAME_ALREADY_ONLINE `even tho the player 'sk8ing' is not online.
I checked your code and I found this:

```
final Player found = Bukkit.getPlayer(name);
if (found != null && found.isOnline()) {
      return DisguiseResponse.FAIL_NAME_ALREADY_ONLINE;
}
```

I guess that Bukkit.getPlayer(name) doesn't check for the exact name match, but rather performs a partial / contains match. The method then returns me ('sk8ingDuck') when I attempt to use the nickname 'sk8ing', even though 'sk8ing' is not an online player.

Can this be fixed?

**Comment by iiAhmedYT** [comment]
fixed in commit a47f222a57a9f4ec3bd5d001438d80d7ca57dc77
